### ISSUE TITLE
Add missing license file

### ISSUE THREAD

**Issue by PureTryOut** [ubports/qtmir#14]
Currently this project is unlicensed, please add one (or multiple) in the root of this project.

**Comment by UniversalSuperBox** [comment]
This project has now moved to GitLab and adopted Debian upstream packaging, which includes a complete debian/copyright file: https://gitlab.com/ubports/core/qtmir/-/blob/main/debian/copyright

This may satisfy any license requirements. If not, please file a new issue on the new repository.
