### ISSUE TITLE
qtmir fails to build against upstream v0.30.0.1 mir release

### ISSUE THREAD

**Issue by WebDrake** [ubports/qtmir#2]
I've just tried to build qtmir against the mir 0.30.0.1 packages in upstream bionic.  The build fails with multiple compiler errors related to API compatibility.

As far as I can tell the failures are down to the following patch introduced into the `xenial` branch and merged into `bionic`: b0929330cfa625236366e1d9b0e6e5fc3313e924

This introduces multiple `#if` rules based on `MIR_SERVER_VERSION`.  These seem unnecessary (qtmir builds if I revert this patch, but not with it) as well as being confusing: the top-level `#if MIR_SERVER_VERSION >= MIR_VERSION_NUMBER(0, 30, 0)` seems to contain other checks within it (such as `#if MIR_SERVER_VERSION >= MIR_VERSION_NUMBER(0, 25, 0)`) which will automatically be true if the top-level `#if` check is.

Absent a compelling reason I would suggest reverting the patch, as I believe it may block a solution to https://github.com/ubports/unity8/issues/30.

**Comment by WebDrake** [comment]
It looks like this is a by-product of the original ubports mir packages being reported as v0.29 even though they were from a more recent copy of the upstream master branch.

As a minimum the existing checks should be replaced by `MIR_SERVER_VERSION >= MIR_VERSION_NUMBER(0, 31, 0)`, but I think it would be a good idea to examine the finer detail of things (because of the nested `#if` checks).

**Comment by mariogrip** [comment]
Yeah sorry about that, I was making that in the middle of a api break before they bumped the version number. So i thought 30 was where the api break was gonna be.

**Comment by WebDrake** [comment]
@mariogrip I'm almost finished with some patches to fix things up properly there.  Will submit a PR shortly.

Could we grab some time to discuss management of this sort of stuff at some point (on Telegram or GitHub, don't mind which)?

**Comment by dobey** [comment]
This appears to no longer be relevant (and I've now fixed the couple of remaining issues which preventing rebuilding qtmir against Mir 1.0, in the bionic branch), so I'm closing. If there's anything relevant still here, please reopen so we can revisit the issues.
