### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [ubports/qtmir#59]
/src/platforms/mirserver/screen.cpp line 87:

 case mir_pixel_format_xbgr_8888:
        if (isLittleEndian()) {
            // 0xRR,0xGG,0xBB,0xXX
            return QImage::Format_RGBX8888;
        } else {
            // 0xXX,0xBB,0xGG,0xRR
            qFatal("[mirserver QPA] "
                   "Qt doesn't support mir_pixel_format_xbgr_8888 in a big endian architecture");
        }
        break;
        break; // <- unreachable

**Comment by UniversalSuperBox** [comment]
I've moved this issue report to https://gitlab.com/ubports/core/qtmir/-/issues/7. Please let me know if it is no longer relevant.
