### ISSUE TITLE
problems with crossbuilder

### ISSUE THREAD

**Issue by wdehoog** [ubports/qtmir#62]
Some things make crossbuilder not working for QtMir. I got it working after changing:
  * adding g++:native to debian/control (like with unity8)
  * created a link in the container: ``sudo ln -s ../../../qt5/bin/moc /usr/lib/x86_64-linux-gnu/qt5/bin/moc``

**Comment by mardy** [comment]
Hi! I'm not sure about the `g++` part, but the second one should be fixed with https://github.com/ubports/crossbuilder/pull/51

**Comment by UniversalSuperBox** [comment]
I've moved this report to https://gitlab.com/ubports/core/qtmir/-/issues/5. If it is no longer relevant, please let me know there.
