### ISSUE TITLE
zero sized software cursor image is invalid

### ISSUE THREAD

**Issue by vanyasem** [ubports/qtmir#9]
Refuses to launch on mir:mesa-x11 with the latest mir
Explanation: https://github.com/MirServer/mir/issues/120

**Comment by vanyasem** [comment]
The easiest workaround is to set cursor size to `1, 1` instead of `0, 0`. For the time while this is still broken.

**Comment by vanyasem** [comment]
I guess this segfault on Arch GNU/Linux is also related: https://paste.ubuntu.com/p/mG45JzCzJr/

**Comment by vanyasem** [comment]
Confirmed, the segfault is gone if you properly set null cursor

**Comment by vanyasem** [comment]
A workaround mentioned by @mariogrip 

https://t.me/ubports_ot/70141

Marius Gripsgard, [14.07.18 03:12]
try setting `export MIR_SERVER_CURSOR=null`

**Comment by vanyasem** [comment]
You can also apply this patch to Mir to force it to always use null cursor (not recommended, breaks `miral-shell`)

[whatDidIDoToMir.patch](https://github.com/ubports/qtmir/files/2318013/whatDidIDoToMir.patch.txt)

**Comment by UniversalSuperBox** [comment]
This issue report has been moved to https://gitlab.com/ubports/core/qtmir/-/issues/4
